defaults: &defaults
  protein_id_regexp: '[\w]+'
  cbi_root_url: 'http://www.cbi.seu.edu.cn/cbi/'

development:
  <<: *defaults
  data_root: 'data'
  pdb_data_root: 'data/pdb'

production:
  <<: *defaults
  data_root: '/data'
  pdb_data_root: '/data/pdb'
