defaults: &defaults
  protein_id_regexp: '[\w]+'
  protein_seq_regexp: '[ARDCQEHIGNLKMFPSTWYV]+'
  email_regexp: '\A[^@]+@[^@]+\z'
  cbi_root_url: 'http://www.cbi.seu.edu.cn/cbi/'
  lock_files_root: <%= File.join(Rails.root, 'tmp', 'locks') %>

development:
  <<: *defaults
  data_root: <%= File.join(Rails.root, 'data') %>
  pdb_data_root: <%= File.join(Rails.root, 'data', 'pdb') %>
  nr_file: <%= File.join(Rails.root, 'data', 'blast', "nr") %>

production:
  <<: *defaults
  data_root: '/data'
  pdb_data_root: '/data/pdb'
  nr_file: '/data/blast/nr'
