defaults: &defaults
  protein_id_regexp: '[\w]+'
  protein_seq_regexp: '(>\w+\n)?[ARDCQEHIGNLKMFPSTWYV\n]+'
  email_regexp: '\A[^@]+@[^@]+\z'
  cbi_root_url: 'http://www.cbi.seu.edu.cn/cbi/'
  lock_files_root: <%= File.join(Rails.root, 'tmp', 'locks') %>

development:
  <<: *defaults
  cbi_root: <%= File.join(Rails.root, 'vendor', 'cbi') %>
  bin_dir: <%= File.join(Rails.root, 'vendor', 'cbi', 'bin') %>
  data_dir: <%= File.join(Rails.root, 'vendor', 'cbi', 'data') %>
  dbname: <%= File.join(Rails.root, 'vendor', 'cbi', 'data', 'nr', 'nr') %>
  tmp_dir: <%= File.join(Rails.root, 'tmp', 'cbi') %>

production:
  <<: *defaults
  cbi_root: '/cbi'
  bin_dir: '/cbi/bin'
  data_dir: '/cbi/data'
  dbname: '/cbi/nr'
  tmp_dir: '/tmp/cbi'

#Test Seq
#TAYDVILAPVLSEKAYAGFAEGKYTFWVHPKATKTEIKNAVETAFKVKVVKVNTLHVRGKKKRLGRYLGKRPDRKKAIVQVAPGQKIEALEG