defaults: &defaults
  protein_id_regexp: '[\w]+'
  protein_seq_regexp: '[ARDCQEHIGNLKMFPSTWYV]+'
  email_regexp: '\A[^@]+@[^@]+\z'
  cbi_root_url: 'http://www.cbi.seu.edu.cn/cbi/'
  lock_files_root: <%= File.join(Rails.root, 'tmp', 'locks') %>

development:
  <<: *defaults
  bin_dir: <%= File.join(Rails.root, 'tmp', 'bin') %>
  data_root: <%= File.join(Rails.root, 'data') %>
  pdb_data_root: <%= File.join(Rails.root, 'data', 'pdb') %>
  nr_file: <%= File.join(Rails.root, 'data', 'blast', "nr") %>
  tmp_root: <%= File.join(Rails.root, 'tmp') %>

production:
  <<: *defaults
  bin_dir: '/cbi/bin'
  data_root: '/cbi/data'
  pdb_data_root: '/cbi/data/pdb'
  nr_file: '/cbi/data/blast/nr'
  tmp_root: '/cbi/data/tmp'